import { spawn } from "node:child_process";
import { createWriteStream, existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { hookCommand, readJsonObject, writeJson } from "../hook-config.js";
import { copyBundledSkills } from "../skills.js";
import {
  parseJsonLine,
  renderSessionTranscriptMarkdown,
  sanitizeTranscriptMessage,
  type SessionTranscriptMessage,
} from "../../session-transcript/markdown.js";
import type { PlatformInstallContext, PlatformInstallResult, PlatformInstaller, WorkingMemoryUpdateInput } from "./types.js";

const generatedMarker = "Generated by Greplica";

// Cursor lifecycle hooks Greplica listens on. beforeSubmitPrompt maps to the
// canonical UserPromptSubmit event and stop maps to Stop (see hook-input.ts).
const cursorHookEvents = ["beforeSubmitPrompt", "stop"] as const;

// Cursor reads user-scoped skills and hooks from ~/.cursor (overridable via
// CURSOR_HOME for tests) and project rules from <repo>/.cursor/rules. Per-prompt
// guidance rides an always-applied rule rather than a hook, because Cursor's
// beforeSubmitPrompt hook cannot inject context into the prompt.
function cursorHome(): string {
  return process.env.CURSOR_HOME ?? join(homedir(), ".cursor");
}

export const cursorInstaller: PlatformInstaller = {
  platform: "cursor",
  install(context: PlatformInstallContext): PlatformInstallResult {
    const skills = copyBundledSkills(join(cursorHome(), "skills"));
    const rulePath = writeCursorRule(context.repoRoot);
    const result: PlatformInstallResult = {
      skills,
      supportsAutoMemoryUpdates: true,
      rules: {
        platform: "cursor",
        configFiles: [rulePath],
      },
    };

    if (context.hooks) {
      const command = hookCommand("cursor");
      const hooksPath = writeCursorHooks(command);
      result.hooks = {
        platform: "cursor",
        configFiles: [hooksPath],
        events: [...cursorHookEvents],
        command,
      };
    }

    return result;
  },
  sessionSourceRef(sessionId: string): string {
    return `cursor-session:${sessionId}`;
  },
  sessionIdFromSourceRef(ref: string): string | undefined {
    return ref.startsWith("cursor-session:") ? ref.slice("cursor-session:".length) : undefined;
  },
  transcriptToMarkdown(transcript: string): string {
    return cursorTranscriptToMarkdown(transcript);
  },
  async runWorkingMemoryUpdate(input: WorkingMemoryUpdateInput): Promise<void> {
    await runCursorAgent(input);
  },
};

// Cursor writes chat transcripts as JSONL where each content line is
// { role: "user" | "assistant", message: { content: [{ type: "text", text }, ...] } }
// and control lines carry a `type` (e.g. "turn_ended"). Project the human/agent
// text into the shared transcript Markdown format.
export function cursorTranscriptToMarkdown(jsonl: string): string {
  const messages: SessionTranscriptMessage[] = [];

  for (const line of jsonl.split("\n")) {
    const event = parseJsonLine(line);
    if (!isRecord(event)) continue;

    const role = cursorTranscriptRole(event.role);
    if (role === undefined) continue;

    const content = isRecord(event.message) ? event.message.content : event.message;
    const text = sanitizeTranscriptMessage(extractTextContent(content));
    if (text.length === 0) continue;

    messages.push({ timestamp: undefined, role, phase: undefined, message: text });
  }

  return renderSessionTranscriptMarkdown({ metadata: {}, messages });
}

function cursorTranscriptRole(role: unknown): SessionTranscriptMessage["role"] | undefined {
  if (role === "user") return "human";
  if (role === "assistant") return "agent";
  return undefined;
}

function extractTextContent(value: unknown): string {
  if (typeof value === "string") return value.trim();
  if (!Array.isArray(value)) return "";

  const parts: string[] = [];
  for (const item of value) {
    if (typeof item === "string") {
      parts.push(item);
    } else if (isRecord(item) && item.type === "text" && typeof item.text === "string") {
      parts.push(item.text);
    }
  }
  return parts.join("\n\n").trim();
}

// Run Cursor's headless CLI (cursor-agent) to execute the working-memory update
// prompt. The prompt is piped on stdin (cursor-agent reads it there in --print
// mode) and the agent's event stream is captured. --force auto-approves tool and
// shell use and --trust skips the workspace trust prompt for unattended runs; the
// workspace is the child's working directory.
//
// cursor-agent ships as a .cmd shim on Windows, which Node cannot spawn without a
// shell, so we run a fixed, interpolation-free command string through the shell —
// safe because no arguments are user-supplied.
const cursorAgentCommand = "cursor-agent --print --force --trust --output-format stream-json";

function runCursorAgent(input: WorkingMemoryUpdateInput): Promise<void> {
  return new Promise((resolve, reject) => {
    const transcript = createWriteStream(input.transcriptPath, { flags: "w" });

    const child = spawn(cursorAgentCommand, {
      cwd: input.cwd,
      env: input.env,
      stdio: ["pipe", "pipe", "inherit"],
      shell: true,
    });

    child.once("error", (error) => {
      transcript.end();
      reject(error);
    });
    child.stdout.pipe(transcript);
    child.stdin.end(input.prompt);
    child.once("close", (exitCode, signal) => {
      transcript.end();
      writeFileSync(
        input.finalMessagePath,
        `Cursor agent update runner exited with code ${exitCode ?? "null"} and signal ${signal ?? "null"}.\n`,
        "utf8",
      );
      resolve();
    });
  });
}

function writeCursorRule(repoRoot: string): string {
  const rulesDir = join(repoRoot, ".cursor", "rules");
  mkdirSync(rulesDir, { recursive: true });
  const rulePath = cursorRulePath(rulesDir);
  writeFileSync(rulePath, cursorRuleContent(), "utf8");
  return rulePath;
}

// Never overwrite a user-authored greplica.mdc: reuse the file only when it was
// generated by Greplica; otherwise fall back to greplica-1.mdc, greplica-2.mdc, ...
function cursorRulePath(rulesDir: string): string {
  const candidates = [join(rulesDir, "greplica.mdc")];
  for (let index = 1; index < 100; index += 1) candidates.push(join(rulesDir, `greplica-${index}.mdc`));

  const generated = candidates.find((candidate) => existsSync(candidate) && readFileSync(candidate, "utf8").includes(generatedMarker));
  if (generated !== undefined) return generated;

  const available = candidates.find((candidate) => !existsSync(candidate));
  if (available !== undefined) return available;

  throw new Error(`Could not find a safe Cursor rule path in ${rulesDir}.`);
}

// Merge our hook command into ~/.cursor/hooks.json without disturbing other
// hooks the user (or another tool) has registered. Re-running is idempotent.
function writeCursorHooks(command: string): string {
  const hooksPath = join(cursorHome(), "hooks.json");
  const base = readJsonObject(hooksPath);
  const version = typeof base.version === "number" ? base.version : 1;
  const hooks = isRecord(base.hooks) ? { ...base.hooks } : {};

  for (const event of cursorHookEvents) {
    const existing = Array.isArray(hooks[event]) ? hooks[event] : [];
    const kept = existing.filter((handler) => !(isRecord(handler) && handler.command === command));
    hooks[event] = [...kept, { command }];
  }

  writeJson(hooksPath, { ...base, version, hooks });
  return hooksPath;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function cursorRuleContent(): string {
  return `---
description: Use Greplica repo memory when working in this project
globs:
  - "**/*"
alwaysApply: true
---
<!-- ${generatedMarker}. Safe to delete; recreated on greplica install. -->

Greplica stores long-term, searchable engineering memory for this repository.

Before broad manual exploration, run:

\`\`\`bash
greplica graph context "<focused question>"
\`\`\`

Use the returned components, flows, claims, and code anchors to decide where to look first.

For a repository that has no memory yet, use the \`greplica-bootstrap\` skill.

Near the end of a useful work session, use the \`greplica-update-working-memory\` skill so durable decisions, constraints, changed workflows, and follow-up tasks are saved.

Do not store secrets, transient debugging chatter, or raw command logs as Greplica memory.
`;
}
